openapi: 3.0.0
info:
  title: Country API
  version: 1.0.0
paths:
  /countries:
    get:
      tags:
        - Countries
      summary: Retrieve all countries
      operationId: getCountries
      responses:
        '200':
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  /countries/{name}:
    get:
      tags:
        - Countries
      summary: Retrieve details about a specific country
      operationId: getCountryByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details about the country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetails'
components:
  schemas:
    Country:
      type: object
      properties:
        name:
          type: string
        flag:
          type: string
    CountryDetails:
      type: object
      properties:
        name:
          type: string
        population:
          type: integer
        capital:
          type: string
        flag:
          type: string